Crud reservation + refactor to Object Oriented
AAU-madboks-collab/madboks-backend pull request #2
Opened 2024-10-28 10:57 UTC by loui981c

![meme](https://github.com/user-attachments/assets/ca9d063a-f776-43ec-adc4-38e0c810e598)

2024-10-28 20:18 UTC, sofiiagran requested changes
A lot of merge conflicts that has to be fixed :')

Ellers, synes jeg koden ser fin ud, det er meget fancy måde at gøre ting på, så jeg skal nok bruge lidt tid på at forstå alt der sker, but it looks good :-)

2024-10-28 20:19 UTC, sofiiagran commented on .github/workflows/ci.yaml
no more linting? :(

2024-10-28 20:21 UTC, sofiiagran commented on package.json
> -    "typescript": "^5.6.3"
behøver vi ikke typescript, eslint ts-node etc?

2024-10-30 10:24 UTC, loui981c commented on .github/workflows/ci.yaml
yesss, men den compiler ts kode før test og kører linting efter by deault :-D

2024-10-30 10:26 UTC, loui981c commented on package.json
> -    "typescript": "^5.6.3"
yes bare refactor så det er der stadigvæk i devDependencies

2024-10-30 16:08 UTC, sofiiagran approved these changes

2024-10-30 19:12 UTC, closed without merging